
let mediaBookmarks
    = "<br />"
    + "<a title='Spotify'target='_parent'href='http://www.spotify.com/'><img id='bookmark' alt='spotify'></a>"
    + "<a title='Pandora'target='_parent'href='https://www.pandora.com'><img id='bookmark' alt='pandoramusic'></a>"
    + "<a title='Lastfm' target='_parent'href='http://www.last.fm/'><img id='bookmark' alt='lastfm'></a>"
    + "<a title='Sound Cloud'target='_parent'href='http://soundcloud.com/' ><img id='bookmark' alt='soundcloud'></a>"
    + "<a title='Audible'target='_parent'href='https://amzn.to/2D4mwBB'><img id='bookmark' alt='audible_com'></a>"
    + "<a title='Youtube'target='_parent'href='https://www.youtube.com/feed/subscriptions'><img id='bookmark' alt='youtube'></a>"
    + "<a title='Netflix'target='_parent'href='http://www.netflix.com/'><img id='bookmark' alt='netflix'></a>"
    + "<a title='Hulu' target='_parent'href='http://www.hulu.com/' ><img id='bookmark' alt='hulu'></a>"
    + "<a title='Aamozn Prime Video' target='_parent'href='https://www.amazon.com/gp/video/storefront' ><img id='bookmark' alt='primevideo'></a>"
    + "<a title='HBO'target='_parent'href='https://play.hbogo.com' ><img id='bookmark' alt='hbo'></a>"
    + "<a title='Dish Anywhere'target='_parent'href='http://www.dishanywhere.com/' ><img id='bookmark' alt='dish'></a>"
    + "<a title='Google Photos'target='_parent'href='https://photos.google.com/' ><img id='bookmark' alt='googlephotos'></a>"
    + "<a title='Photobucket'target='_parent'href='http://photobucket.com/'><img id='bookmark' alt='photobucket'></a>"
    + "<a title='Deviant Art'target='_parent'href='http://www.deviantart.com/' ><img id='bookmark' alt='deviantart'></a>"
    + "<a title='Flickr' target='_parent'href='http://www.flickr.com/' ><img id='bookmark' alt='flickr'></a>"
    + "<a title='imgflip' target='_parent'href='https://imgflip.com/' ><img id='bookmark' alt='imgflip'></a>"
    + "<a title='Beehive'target='_parent'href='http://beehivecollective.org/'><img id='bookmark' alt='beehivedesign'></a>"
    + "<a title='Tumblr' target='_parent'href='https://www.tumblr.com/dashboard' ><img id='bookmark' alt='tumblr'></a>"
    + "<a title='Gravit' target='_parent'href='https://designer.io/' ><img id='bookmark' alt='gravitdesigner'></a>"
    + "<a title='ShutterStock' target='_parent'href='http://www.shutterstock.com/?rid=224491653' ><img id='bookmark' alt='shutterstock'></a>"
    + "<a title='Blogger'target='_parent'href='https://www.blogger.com/' ><img id='bookmark' alt='blogger'></a>"
    + "<a title='The Late Show'target='pageContent'href='https://www.youtube.com/channel/UCMtFAi84ehTSYSE9XoHefig/videos' ><img id='bookmark' alt='colbertlateshow'></a>";
document.body.innerHTML += mediaBookmarks;