let referenceBookmarks
    = "<a title='Reference'     target='contentframe'   href='./reference/index.html'                   ><img id='bookmark' alt='reference'></a>"
    + "<a title='FINVIZ_com'        target='_parent' href='https://finviz.com/' ><img id='bookmark' alt='FINVIZ_com'></a>"
    + "<a title='FINVIZ_com'        target='_parent' href='https://finviz.com/' ><img id='bookmark' alt='FINVIZ_com'></a>"
    + "<a title='FINVIZ_com'        target='_parent' href='https://finviz.com/' ><img id='bookmark' alt='FINVIZ_com'></a>"
    + "<a title='Ancestry'      target='_parent'        href='https://www.ancestry.com/'                ><img id='bookmark' alt='Ancestry'></a>"
    + "<a title='23 & Me'       target='_parent'        href='https://www.23andme.com/'                 ><img id='bookmark' alt='23andMe'></a>"
    + "<a title='Wikipedia'target='_parent'href='http://wikipedia.org/'><img id='bookmark' alt='wikipedia'></a>"
    + "<a title='IMDB' target='_parent'href='http://www.imdb.com/' ><img id='bookmark' alt='imdb'></a>"
    + "<a title='ehow' target='_parent'href='http://www.ehow.com/' ><img id='bookmark' alt='ehow'></a>"
    + "<a title='Almanac'target='_parent'href='https://www.almanac.com/' ><img id='bookmark' alt='almanac'></a>"
    + "<a title='Ted'target='_parent'href='https://www.ted.com'><img id='bookmark' alt='tedtalks'></a>"
    + "<a title='Allrecipes' target='_parent'href='https://www.allrecipes.com/'><img id='bookmark' alt='allrecipes'></a>"
    + "<a title='Life Hacker'target='_parent'href='https://lifehacker.com/'><img id='bookmark' alt='lifehacker'></a>"
    + "<a title='Khan Academy' target='_parent'href='https://www.khanacademy.org/' ><img id='bookmark' alt='khanacademy'></a>"
    + "<a title='Font Awesome' target='_parent'href='https://fontawesome.com/' ><img id='bookmark' alt='fontawesome'></a>"
    + "<a title='Ptable' target='_parent'href='https://www.ptable.com/'><img id='bookmark' alt='ptable'></a>"
    + "<a title='Dictionary' target='_parent'href='http://dictionary.reference.com/' ><img id='bookmark' alt='dictionarycom'></a>"
    + "<a title='Duolingo' target='_parent'href='https://www.duolingo.com' ><img id='bookmark' alt='duolingo'></a>"
    + "<a title='Kurzgesagt' target='_parent'href='https://www.youtube.com/user/Kurzgesagt'><img id='bookmark' alt='Kurz_Gesagt'></a>"
    + "<a title='Crash Course' target='_parent'href='https://www.youtube.com/user/crashcourse' ><img id='bookmark' alt='thecrashcourse'></a>";
document.body.innerHTML += referenceBookmarks;