let investingBookmarks
    = "<a title='Investing'    	target='contentframe'href='./investing/index.html'                    ><img id='bookmark' alt='investing'></a>"
    + "<a title='E*Trade'		target='_parent'href='https://us.etrade.com/home' ><img id='bookmark' alt='etrade'></a>"
    + "<a title='fidelity'     target='_parent' href='https://oltx.fidelity.com/ftgw/fbc/oftop/portfolio#summary' ><img id='bookmark' alt='fidelity'></a>"
    + "<a title='Robinhood'     target='_parent' href='https://join.robinhood.com/josephg4312' ><img id='bookmark' alt='RobinhoodApp'></a>"
    + "<a title='Acorns'        target='_parent' href='https://www.acorns.com/' ><img id='bookmark' alt='acorns'></a>"
    + "<a title='webull'  target='_parent' href='https://act.webull.com/iv/e5OOcG2gCh7s/71n/inviteUs/' ><img id='bookmark' alt='webull'></a>"
    + "<a title='Coinbase'      target='_parent' href='https://www.coinbase.com/join/jgoulette_4hiaeA' ><img id='bookmark' alt='coinbase'></a>"
    + "<a title='fundrise'      target='_parent' href='https://www.fundrise.com/r/pp1rp7' ><img id='bookmark' alt='fundrise'></a>"
    + "<a title='Worthy'      target='_parent' href='https://worthybonds.com/?r=ikhfn' ><img id='bookmark' alt='Worthy'></a>"
    + "<a title='Gem Select'            target='_parent'href='https://www.gemselect.com/index.php'              ><img id='bookmark' alt='GemSelect'></a>"
    + "<a title='Apmex'                 target='_parent'href='https://www.apmex.com/account/portfolio'                           ><img id='bookmark' alt='apmex'></a>"
    + "<a title='ucoin'                 target='_parent'href='https://en.ucoin.net/?ref=ZvVW2bgHAaqB2UEt'                           ><img id='bookmark' alt='ucoin'></a>"
    + "<a title='JMBullion'             target='_parent'href='https://www.JMBullion.com/'                           ><img id='bookmark' alt='JMBullion'></a>"
    + "<a title='https://luciteria.com/'             target='_parent'href='https://luciteria.com/'                           ><img id='bookmark' alt='luciteria'></a>"
    + "<a title='FINVIZ_com'        target='_parent' href='https://finviz.com/' ><img id='bookmark' alt='FINVIZ_com'></a>"
    + "<a title='https://www.investopedia.com/https://www.investopedia.com/'        target='_parent' href='https://www.investopedia.com/' ><img id='bookmark' alt='investopedia'></a>"
    + "<a title='FINVIZ_com'        target='_parent' href='https://finviz.com/' ><img id='bookmark' alt='FINVIZ_com'></a>"
    + "<a title='Investing'     target='contentframe'href='./investing/index.html'                    ><img id='bookmark' alt='investing'></a>";
document.body.innerHTML += investingBookmarks;