let financeBookmarks
    = "<a title='Finance'    	target='contentframe'href='./finance/index.html'                    ><img id='bookmark' alt='finance'></a>"
    + "<a title='Paypal' 		target='_parent'href='https://www.paypal.com/'><img id='bookmark' alt='paypal'></a>"
    + "<a title='E*Trade'		target='_parent'href='https://us.etrade.com/home' ><img id='bookmark' alt='etrade'></a>"
    + "<a title='Robinhood'     target='_parent' href='https://robinhood.com' ><img id='bookmark' alt='RobinhoodApp'></a>"
    + "<a title='Acorns'        target='_parent' href='https://www.acorns.com/' ><img id='bookmark' alt='acorns'></a>"
    + "<a title='            '  target='_parent' href='                                     ' ><img id='bookmark' alt='                              '></a>"
    + "<a title='ShrimpyApp'  target='_parent' href='https://shrimpy.io/referral?r=9ZfJPAj__' ><img id='bookmark' alt='ShrimpyApp'></a>"
    + "<a title='binance'       target='_parent' href='https://www.binance.com/en/my/wallet/account/overview' ><img id='bookmark' alt='binance'></a>"
    + "<a title='BinanceUS'     target='_parent' href='https://www.binance.us/en/usercenter/wallet/balances' ><img id='bookmark' alt='BinanceUS'></a>"
    + "<a title='AtomicWallet'  target='_parent' href='https://atomicwallet.io/' ><img id='bookmark' alt='AtomicWallet'></a>"
    + "<a title='Coinbase'      target='_parent' href='https://www.coinbase.com/' ><img id='bookmark' alt='coinbase'></a>"
    + "<a title='Coinbase'      target='_parent' href='https://www.coinbase.com/' ><img id='bookmark' alt='coinbase'></a>"
    + "<a title='Coinbase'      target='_parent' href='https://www.coinbase.com/' ><img id='bookmark' alt='coinbase'></a>"
    + "<a title='Coinbase'      target='_parent' href='https://www.coinbase.com/' ><img id='bookmark' alt='coinbase'></a>"
    + "<a title='Coinbase'      target='_parent' href='https://www.coinbase.com/' ><img id='bookmark' alt='coinbase'></a>"
    + "<a title='ShutterStock Affil' target='_parent'href='https://submit.shutterstock.com/?ref=224491653' ><img id='bookmark' alt='ShutterstockReq'></a>"
    + "<a title='Amazon Associate' target='_parent'href='https://affiliate-program.amazon.com/home'><img id='bookmark' alt='AmazonAssociate'></a>"
    + "<a title='Analytics' target='_parent'href='https://analytics.google.com'><img id='bookmark' alt='googleanalytics'></a>";
document.body.innerHTML += financeBookmarks;