let gamesBookmarks
    = "<a title='Games'    target='contentframe'href='./games/index.html'                    ><img id='bookmark' alt='game'></a>"
    + "<a title='Twitch' target='_parent'href='https://www.twitch.tv'><img id='bookmark' alt='twitch'></a>"
    + "<a title='Discord'target='_parent'href='https://discordapp.com' ><img id='bookmark' alt='discordapp'></a>"
    + "<a title='Gewey Referral'    target='contentframe'href='./shopping/referral.html'                    ><img id='bookmark' alt='blank'></a>"
    + "<a title='Runescape'target='_parent'href='http://runescape.com/'><img id='bookmark' alt='runescape'></a>"
    + "<a title='Old SChool RS'target='_parent'href='https://oldschool.runescape.com'><img id='bookmark' alt='oldschoolrs'></a>"
    + "<a title='Rune Wiki'target='_parent'href='https://runescape.wiki/'><img id='bookmark' alt='RSWiki'></a>"
    + "<a title='Rune Tips'target='_parent'href='https://www.tip.it/runescape/'><img id='bookmark' alt='runetips'></a>"
    + "<a title='Rune HQ'target='_parent'href='https://www.runehq.com' ><img id='bookmark' alt='officialrunehq'></a>"
    + "<a title='Gewey Referral'    target='contentframe'href='./shopping/referral.html'                    ><img id='bookmark' alt='blank'></a>"
    + "<a title='minecraft'target='_parent'href='https://minecraft.net/' ><img id='bookmark' alt='minecraft'></a>"
    + "<a title='minecraft wiki'target='_parent'https://minecraft.gamepedia.com/Minecraft_Wiki' ><img id='bookmark' alt='minecraftwiki'></a>"
    + "<a title='Forge'target='_parent'href='https://files.minecraftforge.net/'><img id='bookmark' alt='ForgeDevTeam'></a>"
    + "<a title='FTBWiki'target='_parent'href='https://ftb.gamepedia.com/FTB_Wiki/'><img id='bookmark' alt='ftb_team'></a>"
    + "<a title='MCREATOR' target='_parent'href='https://mcreator.net/'><img id='bookmark' alt='PyloDEV'></a>"
    + "<a title='Crafatar' target='_parent'href='https://crafatar.com/'><img id='bookmark' alt='Crafatar'></a>"
    + "<a title='Gewey Referral'    target='contentframe'href='./shopping/referral.html'                    ><img id='bookmark' alt='blank'></a>"
    + "<a title='The Sims' target='_parent'href='https://www.ea.com/games/the-sims'><img id='bookmark' alt='TheSims'></a>"
    + "<a title='Mod The Sims' target='_parent'href='http://www.modthesims.info/'><img id='bookmark' alt='modthesimsinfo'></a>"
    + "<a title='Gewey Referral'    target='contentframe'href='./shopping/referral.html'                    ><img id='bookmark' alt='blank'></a>"
    + "<a title='Steam'target='_parent'href='https://store.steampowered.com/'><img id='bookmark' alt='steam_games'></a>"
    + "<a title='Origin'target='_parent'href='https://www.origin.com/'><img id='bookmark' alt='origininsider'></a>"
    + "<a title='Guild Wars 2' target='_parent'href='https://www.guildwars2.com/'><img id='bookmark' alt='GuildWars2'></a>"
    + "<a title='ElderScrollsOnline' target='_parent'href='https://www.elderscrollsonline.com/'><img id='bookmark' alt='tesonline'></a>"
    + "<a title='Wizard101' target='_parent'href='https://www.wizard101.com/'><img id='bookmark' alt='wizard101'></a>"
    + "<a title='XBOX' target='_parent'href='http://www.xbox.com/en-US/' ><img id='bookmark' alt='xbox'></a>"
    + "<a title='starcraft2' target='_parent'https://starcraft2.com/en-us/' ><img id='bookmark' alt='starcraft2'></a>"
    + "<a title='Magic the Gathering'target='_parent'href='https://magic.wizards.com/en' ><img id='bookmark' alt='wizards_magic'></a>";
document.body.innerHTML += gamesBookmarks;


