let graveyardBookmarks
    = "<a title='Gewey Referral'    target='contentframe'href='./shopping/referral.html'                    ><img id='bookmark' alt='blank'></a>"
    + "<a title='ESPN' target='_parent'href='http://espn.go.com/'><img id='bookmark' alt='espn'></a>"
    + "<a title='Sports Illustrated' target='_parent'href='https://www.si.com/'><img id='bookmark' alt='sinow'></a>"
    + "<a title='Nascar' target='_parent'href='https://www.nascar.com/'><img id='bookmark' alt='nascar'></a>"
    + "<a title='MySpace'target='_parent'href='http://home.myspace.com/' ><img id='bookmark' alt='myspace'></a>"
    + "<a title='ning' target='_parent'href='http://www.ning.com/' ><img id='bookmark' alt='ning'></a>"
    + "<a title='Delicious'target='_parent'href='http://delicious.com/'><img id='bookmark' alt='delicious'></a>"
    + "<a title='Dish Anywhere'     target='_parent'href='http://www.dishanywhere.com/'                 ><img id='bookmark' alt='dish'              ></a>"
    + "<a title='hi5'target='_parent'href='http://hi5.com/'><img id='bookmark' alt='hi5'></a>"
    + "<a title='designfloat'target='_parent'href='http://www.designfloat.com/'><img id='bookmark' alt='designfloat'></a>"
    + "<a title='Dothdash' target='_parent'href='http://www.dotdash.com/'><img id='bookmark' alt='dotdashco'></a>"
    + "<a title='Bing' target='_parent'href='http://go.microsoft.com/?linkid=9778718&rrid=_1842a0ac-32d7-bb98-f569-514a0a9eb5ad'><img id='bookmark' alt='bing'></a>"
    + "<a title='Guru3D' target='_parent'href='https://www.guru3d.com/'><img id='bookmark' alt='guru_3d'></a>"
    + "<a title='Beehive'           target='_parent'href='http://beehivecollective.org/'                ><img id='bookmark' alt='beehivedesign'     ></a>"
    + "<a title='Pandora'target='_parent'href='https://www.pandora.com'><img id='bookmark' alt='pandoramusic'></a>"
    + "<a title='Lastfm' target='_parent'href='http://www.last.fm/'><img id='bookmark' alt='lastfm'></a>"
    + "<a title='Photobucket'       target='_parent'href='http://photobucket.com/'                      ><img id='bookmark' alt='photobucket'       ></a>"
    + "<a title='Flickr'            target='_parent'href='http://www.flickr.com/'                       ><img id='bookmark' alt='flickr'            ></a>"
    + "<a title='HBO'               target='_parent'href='https://play.hbogo.com'                       ><img id='bookmark' alt='hbo'               ></a>"
    + "<a title='AVG'target='_parent'href='http://www.avg.com/us-en/homepage'><img id='bookmark' alt='avgfree'></a>"
    + "<a title='Apple'target='_parent'href='http://www.apple.com/'><img id='bookmark' alt='apple'></a>"
    + "<a title='uTorrent' target='_parent'href='https://www.utorrent.com/'><img id='bookmark' alt='utorrent'></a>"
    + "<a title='Adobe Reader' target='_parent'href='http://get.adobe.com/reader/' ><img id='bookmark' alt='acrobat' /></a>"
    + "<a title='Adobe Air'target='_parent'href='http://get.adobe.com/air/'><img id='bookmark' alt='air_devs' /></a>"
    + "<a title='Adobe Flash'target='_parent'href='http://get.adobe.com/flashplayer/'><img id='bookmark' alt='adobeflash' /></a>"
    + "<a title='Sound Cloud'target='_parent'href='http://soundcloud.com/' ><img id='bookmark' alt='soundcloud'></a>"
    + "<a title='Chase'target='_parent'href='https://www.chase.com/' ><img id='bookmark' alt='chase'></a>"
    + "<a title='Bank of America'target='_parent'href='https://www.bankofamerica.com/' ><img id='bookmark' alt='bankofamerica'></a>"
    + "<a title='Ad Fly' target='_parent'href='https://join-adf.ly/2964346'><img id='bookmark' alt='adfly'></a>"
    + "<a title='AOL [HTTPS]'target='_parent'href='https://www.aol.com/' ><img id='bookmark' alt='aol'></a>"
    + "<a title='Craigslist'            target='_parent'href='http://www.craigslist.org/'                       ><img id='bookmark' alt='craigslist'></a>"
    + "<a title='binance'       target='_parent' href='https://www.binance.com/en/my/wallet/account/overview' ><img id='bookmark' alt='binance'></a>"
    + "<a title='BinanceUS'     target='_parent' href='https://www.binance.us/en/usercenter/wallet/balances' ><img id='bookmark' alt='BinanceUS'></a>"
    + "<a title='9animeOfficial'    target='_parent'href='https://www12.9anime.to/home'                 ><img id='bookmark' alt='9animeOfficial'    ></a>"
    + "<a title='Last Week Tonight' target='_parent'href='https://www.youtube.com/user/LastWeekTonight' ><img id='bookmark' alt='LastWeekTonight'   ></a>"
    + "<a title='Real Time'         target='_parent'href='https://www.youtube.com/user/RealTime'        ><img id='bookmark' alt='RealTimers'        ></a>"
    + "<a title='The Late Show'     target='pageContent'href='https://www.youtube.com/channel/UCMtFAi84ehTSYSE9XoHefig/videos' ><img id='bookmark' alt='colbertlateshow'></a>"
    + "<a title='Misfits Market'        target='_parent'href='https://www.misfitsmarket.com/'                   ><img id='bookmark' alt='misfitsmarket'></a>"
    + "<a title='Technorati' target='_parent'href='http://technorati.com/' ><img id='bookmark' alt='technorati'></a>";
document.body.innerHTML += graveyardBookmarks;
