let referenceBookmarks
    = "<a title='Gewey Referral'    target='contentframe'href='./shopping/referral.html'                    ><img id='bookmark' alt='blank'></a>"
    + "<a title='Wikipedia'target='_parent'href='http://wikipedia.org/'><img id='bookmark' alt='wikipedia'></a>"
    + "<a title='IMDB' target='_parent'href='http://www.imdb.com/' ><img id='bookmark' alt='imdb'></a>"
    + "<a title='ehow' target='_parent'href='http://www.ehow.com/' ><img id='bookmark' alt='ehow'></a>"
    + "<a title='Almanac'target='_parent'href='https://www.almanac.com/' ><img id='bookmark' alt='almanac'></a>"
    + "<a title='Ted'target='_parent'href='https://www.ted.com'><img id='bookmark' alt='tedtalks'></a>"
    + "<a title='Allrecipes' target='_parent'href='https://www.allrecipes.com/'><img id='bookmark' alt='allrecipes'></a>"
    + "<a title='Life Hacker'target='_parent'href='https://lifehacker.com/'><img id='bookmark' alt='lifehacker'></a>"
    + "<a title='Bleeping Computer'target='_parent'href='https://www.bleepingcomputer.com/'><img id='bookmark' alt='BleepinComputer'></a>"
    + "<a title='w3 schools' target='_parent'href='http://www.w3schools.com/'><img id='bookmark' alt='w3schoolsonline'></a>"
    + "<a title='stack overflow' target='_parent'href='https://stackoverflow.com/' ><img id='bookmark' alt='StackOverflow'></a>"
    + "<a title='github' target='_parent'href='https://github.com/'><img id='bookmark' alt='github'></a>"
    + "<a title='Khan Academy' target='_parent'href='https://www.khanacademy.org/' ><img id='bookmark' alt='khanacademy'></a>"
    + "<a title='codecademy' target='_parent'href='https://www.codecademy.com//' ><img id='bookmark' alt='codecademy'></a>"
    + "<a title='freecodecamp' target='_parent'href='https://learn.freecodecamp.org/' ><img id='bookmark' alt='freeCodeCamp'></a>"
    + "<a title='Tensorflow' target='_parent'href='https://js.tensorflow.org/' ><img id='bookmark' alt='tensorflow'></a>"
    + "<a title='Font Awesome' target='_parent'href='https://fontawesome.com/' ><img id='bookmark' alt='fontawesome'></a>"
    + "<a title='CodePen.IO' target='_parent'href='https://codepen.io/'><img id='bookmark' alt='codepen'></a>"
    + "<a title='Material.IO'target='_parent'href='https://material.io/' ><img id='bookmark' alt='materialdesign'></a>"
    + "<a title='Open Culture' target='_parent'href='http://www.openculture.com'><img id='bookmark' alt='openculture'></a>"
    + "<a title='Ptable' target='_parent'href='https://www.ptable.com/'><img id='bookmark' alt='ptable'></a>"
    + "<a title='MIT APP INVENTOR' target='_parent'href='http://ai2.appinventor.mit.edu/'><img id='bookmark' alt='mitappinventor'></a>"
    + "<a title='Dictionary' target='_parent'href='http://dictionary.reference.com/' ><img id='bookmark' alt='dictionarycom'></a>"
    + "<a title='Duolingo' target='_parent'href='https://www.duolingo.com' ><img id='bookmark' alt='duolingo'></a>"
    + "<a title='Kurzgesagt' target='_parent'href='https://www.youtube.com/user/Kurzgesagt'><img id='bookmark' alt='Kurz_Gesagt'></a>"
    + "<a title='Crash Course' target='_parent'href='https://www.youtube.com/user/crashcourse' ><img id='bookmark' alt='thecrashcourse'></a>";
document.body.innerHTML += referenceBookmarks;